name: Weather Data Processing

on:
    schedule:
      - cron:  '0 10 * * *'
    workflow_dispatch:

jobs:
  run_weather_script:
    runs-on: ubuntu-latest  # Use a Linux virtual machine (Ubuntu)

    permissions:
      contents: write  # This gives permission to commit and push changes to the repository

    steps:

    # Step 1: Use Node.js 20
    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Step 2: Checkout the repository to get access to the scripts and files
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 3: Run the weather.sh script (no need to install wget if it's already installed)
    - name: Run weather.sh script
      run: |
        chmod +x weather.sh  # Make sure the script is executable
        ./weather.sh         # Run the script to gather weather data
    # Step 4: Commit and push changes
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Explicitly passing the token
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Run daily stocks script" || echo "No changes to commit"
        git push
